from pathlib import Path

from llm.client import LLMClient
from llm.schemas import LLMRequest
from llm.tools import sql_plan_tool
from llm.utils import extract_json, require_keys
from orchestrator.context import OrchestratorContext
from settings import get_settings
from shared.types import QueryCard, QueryPlan
from tools.sql.estimator import estimate_cost
from tools.sql.optimizer import optimize_sql
from persistence.datasets import latest_dataset


def run(ctx: OrchestratorContext) -> OrchestratorContext:
    settings = get_settings()
    metric = ctx.metrics[0].name if ctx.metrics else "metric"
    dataset = latest_dataset()
    sql = f"SELECT '{metric}' AS metric, 0.421 AS value, 'all' AS segment"
    if settings.llm_provider:
        base_prompt_path = Path(__file__).resolve().parents[2] / "llm" / "prompts" / "system.md"
        base_prompt = base_prompt_path.read_text(encoding="utf-8")
        prompt_path = Path(__file__).resolve().parents[2] / "llm" / "prompts" / "sql_gen.md"
        prompt = prompt_path.read_text(encoding="utf-8")
        client = LLMClient()
        response = client.complete(
            LLMRequest(
                system_prompt=base_prompt,
                user_prompt=(
                    f"{prompt}\n\n问题：{ctx.clarified_question}\n"
                    f"指标：{metric}\n引擎：{settings.sql_engine}\n"
                    "请生成 SQL 方案 JSON。"
                ),
            ),
            tools=[sql_plan_tool()],
            tool_choice="auto",
            trace=ctx.llm_trace,
            trace_messages=ctx.llm_trace_messages,
            trace_label="sql_plan",
        )
        parsed = None
        if response.tool_outputs:
            parsed = response.tool_outputs[0]
        elif settings.llm_strict_json:
            parsed = extract_json(response.content)
        if parsed and require_keys(parsed, ["sql", "assumptions", "tables"]):
            sql = parsed["sql"]
        elif not settings.llm_strict_json and response.content.strip().lower().startswith("select"):
            sql = response.content.strip()
    if dataset and any(keyword in (ctx.clarified_question or ctx.task_spec.question) for keyword in ["数据集", "上传", "表", dataset["table"]]):
        table = dataset["table"]
        sql = f'SELECT * FROM "{table}" LIMIT 200'
        ctx.warnings.append(f"Using latest dataset table: {table}")
    sql = optimize_sql(sql, settings.sql_engine)
    params = ctx.clarify_params.filters if ctx.clarify_params else {}
    plan = QueryPlan(
        engine="sqlite" if dataset else settings.sql_engine,
        sql=sql,
        assumptions=parsed["assumptions"] if parsed else ["sample plan"],
        params=params,
        tables=parsed["tables"] if parsed else ([dataset["table"]] if dataset else ["analytics.metrics"]),
    )
    ctx.query_plan = plan
    estimate = estimate_cost(sql, plan.engine)
    if estimate.scan_bytes and estimate.scan_bytes > settings.max_scan_bytes:
        ctx.warnings.append("Estimated scan exceeds threshold; consider sampling.")
    ctx.queries.append(
        QueryCard(
            title="Primary query",
            sql=sql,
            engine=plan.engine,
            params=params,
            scan_cost=estimate.scan_cost,
            estimated_cost=estimate.scan_cost,
            notes="Generated by planner",
        )
    )
    return ctx
